print("##############################")
print("#  \t   \t      \t     #")
print("#   Clarissa Dhea Allisya    #")
print("#       2410817220023        #")
print("#  \t   \t      \t     #")
print("##############################")